### ISSUE TITLE
[unplanned] Promote docker configuration to a first-class object

### ISSUE THREAD

**Issue by btoll** [algorand/mule#36]
This accomplishes the following goals:
1. Relieves the dev of having to define `docker.Version` and `shell.docker.Ensure`.  These operations now become the responsibility of the new class.
2. Reduces much of the config duplication that we see in all the mule yaml files.

For example, the following is existing yaml configuration and can be reduced:
```
tasks:
  - task: docker.Version
    configFilePath: scripts/configure_dev-deps.sh

  - task: shell.docker.Ensure
    name: docker-ubuntu
    image: algorand/go-algorand-docker-linux-ubuntu
    version: '{{ docker.Version.outputs.version }}'
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    dependencies: docker.Version

  - task: docker.Make
    name: deb
    docker:
      image: algorand/go-algorand-docker-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: package WORKDIR=/projects/go-algorand

  - task: docker.Make
    name: deb-sign
    docker:
      image: algorand/go-algorand-ci-linux-ubuntu
      version: '{{ docker.Version.outputs.version }}'
      workDir: /projects/go-algorand
    target: sign WORKDIR=/projects/go-algorand
```

It can look like:
```
tasks:
  - task: docker.Image
    name: ubuntu
    dockerFilePath: docker/build/docker.ubuntu.Dockerfile
    image: algorand/go-algorand-docker-linux-ubuntu
    version: scripts/configure_dev-deps.sh.md
    workDir: /projects/go-algorand

  - task: docker.Make
    name: package
    target: package
    dependencies: docker.Image.ubuntu

  - task: docker.Make
    name: sign
    target: sign
    dependencies: docker.Image.ubuntu
```
Further reductions are then afforded in the `jobs` section of the yaml config.
